### ISSUE TITLE
Which resistors to use for I2C?

### ISSUE THREAD

**Issue by Xyverz** [nicinabox/lets-split-guide#19]
I don't see any suggestions for parts for the I2C resistors - either which model or how many are needed. I'm interested in using I2C on my next build and it'd be helpful to know this.

**Comment by nicinabox** [comment]
You'll probably get an answer on /r/olkb or /r/mk. I don't actually know.

**Comment by Duckle29** [comment]
4.7k resistors, and only on one half.

The value isn't overly critical to be honest, but 4.7k is the spec.
