### ISSUE TITLE
Re: RGB Underglow

### ISSUE THREAD

**Issue by Khord** [nicinabox/lets-split-guide#3]
https://camo.githubusercontent.com/6251f238a6d77ca203f50d6ee6f5ea8e0a81675b/687474703a2f2f692e696d6775722e636f6d2f6d5379704335792e6a7067

It is redundant to solder the 5V and GND to the pro micro on the primary side. Only the data is directional, and the power is already flowing to your solder points at the primary TRRS jack to power the slave pro micro. (Or vice versa; unneeded power wires at TRRS jack if keeping pro micro power wires)

http://i.imgur.com/Uj0o7qr.jpg

**Comment by nicinabox** [comment]
👍 I'd actually updated my wiring to this a while ago and have been meaning to take some new pictures.

**Comment by Xyverz** [comment]
I have a question about this - can the power wires that you're connecting be on any part of the LED strip, or is it necessary to have them somewhere in the middle and not at the far end? It might be good to clarify this.

**Comment by nicinabox** [comment]
@Xyverz VCC and GND can be anywhere on the strip. DO needs to be on the last one. I'm more a fan of putting all the connections together, but splitting them up is fairly common.
